name: mp3_music_converter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  audioplayers:
  flutter_radio: ^0.1.8
  cached_network_image: ^2.5.0
  marquee: ^1.7.0
  hive_flutter: ^0.3.1
  hive: ^1.4.4+1
  file_picker: ^2.1.6
  share: ^0.6.5+4
  flutter_downloader: ^1.5.2
  permission_handler: ^5.1.0+2
  http: ^0.12.2
  path_provider: ^1.6.27
  pin_entry_text_field: ^0.1.4
  route_transitions: ^1.0.2
  image_picker: ^0.6.7+22
  font_awesome_flutter: ^9.0.0
  toast: ^0.1.5
  flutter_spinkit: ^4.1.2+1
  jaynetwork: ^0.0.1
  provider: ^4.3.2+2
  video_thumbnail: 0.3.3
  ntp: ^1.0.5
  time_machine: ^0.9.16
  hive_listener:
  intl: ^0.16.0
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  downloads_path_provider: ^0.1.0
  dots_indicator: ^2.0.0
  geolocator: ^6.2.1
  geocoder: ^0.2.1
  intent: ^1.4.0
  flutter_switch: ^0.3.1
  rave_flutter: ^0.0.9-alpha+2
  flutter_audio_recorder: ^0.5.5
  audio_service: ^0.16.2+1
  google_maps_flutter:
  geocoding:
  firebase_storage:
  firebase_core:
  cloud_functions:
  google_mobile_ads: ^0.13.0
  uuid:
  flutter_speech: ^2.0.0
  image_downloader: ^0.30.0
  firebase_database: ^6.0.0
  loading_overlay: ^0.3.0
  flutter_paystack: ^1.0.4+1
  on_audio_query: ^1.0.2
  flutter_tts: ^2.1.0
  pdf_text: ^0.4.0
  pdf_render: ^0.69.0
  pdf: ^2.1.0
  dropdown_search: ^0.6.3
  google_sign_in: ^4.5.9
  equalizer: 0.0.2+2
  flutter_xlider: ^3.4.0
  pull_to_refresh: ^2.0.0
  page_transition: ^1.1.7+4
  syncfusion_flutter_pdf: any
  printing: ^4.0.0
  native_pdf_renderer: any
  image_gallery_saver: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_pay: ^1.0.2

dependency_overrides:
  flutter_svg: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner:

#flutter_icons:
#  android: true
#  ios: true
#  remove_alpha_ios: true
#  image_path: "assets/youtubeaudiologo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Thin.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
